// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: api/server/v1/server.proto

package serverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUser) Reset() {
	*x = OnlineUser{}
	mi := &file_api_server_v1_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUser) ProtoMessage() {}

func (x *OnlineUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUser.ProtoReflect.Descriptor instead.
func (*OnlineUser) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnlineUser) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type PushOnlineUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*OnlineUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushOnlineUsersRequest) Reset() {
	*x = PushOnlineUsersRequest{}
	mi := &file_api_server_v1_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushOnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushOnlineUsersRequest) ProtoMessage() {}

func (x *PushOnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushOnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*PushOnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{1}
}

func (x *PushOnlineUsersRequest) GetUsers() []*OnlineUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Upload        int64                  `protobuf:"varint,2,opt,name=upload,proto3" json:"upload,omitempty"`
	Download      int64                  `protobuf:"varint,3,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_api_server_v1_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{2}
}

func (x *UserTraffic) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTraffic) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *UserTraffic) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

type PushUserTrafficRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traffic       []*UserTraffic         `protobuf:"bytes,1,rep,name=traffic,proto3" json:"traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushUserTrafficRequest) Reset() {
	*x = PushUserTrafficRequest{}
	mi := &file_api_server_v1_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushUserTrafficRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushUserTrafficRequest) ProtoMessage() {}

func (x *PushUserTrafficRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushUserTrafficRequest.ProtoReflect.Descriptor instead.
func (*PushUserTrafficRequest) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{3}
}

func (x *PushUserTrafficRequest) GetTraffic() []*UserTraffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type PushServerStatusRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Cpu       float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem       float64                `protobuf:"fixed64,2,opt,name=mem,proto3" json:"mem,omitempty"`
	Disk      float64                `protobuf:"fixed64,3,opt,name=disk,proto3" json:"disk,omitempty"`
	UpdatedAt int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// version 是节点正在运行的版本；latest_version 是节点自己查到的上游最新版
	// （让节点查，面板就不必访问外网）。两者都可能为空，不能当作必填。
	// 【字段号必须和另一个仓库里的同名消息一致】见本文件顶部关于 wire 兼容的说明。
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	LatestVersion string `protobuf:"bytes,6,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushServerStatusRequest) Reset() {
	*x = PushServerStatusRequest{}
	mi := &file_api_server_v1_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushServerStatusRequest) ProtoMessage() {}

func (x *PushServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushServerStatusRequest.ProtoReflect.Descriptor instead.
func (*PushServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{4}
}

func (x *PushServerStatusRequest) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *PushServerStatusRequest) GetMem() float64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *PushServerStatusRequest) GetDisk() float64 {
	if x != nil {
		return x.Disk
	}
	return 0
}

func (x *PushServerStatusRequest) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *PushServerStatusRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PushServerStatusRequest) GetLatestVersion() string {
	if x != nil {
		return x.LatestVersion
	}
	return ""
}

// Result is the common error and no-data response envelope. Its fields match
// the JSON API's code and msg fields.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_api_server_v1_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServerBasic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushInterval  int64                  `protobuf:"varint,1,opt,name=push_interval,json=pushInterval,proto3" json:"push_interval,omitempty"`
	PullInterval  int64                  `protobuf:"varint,2,opt,name=pull_interval,json=pullInterval,proto3" json:"pull_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerBasic) Reset() {
	*x = ServerBasic{}
	mi := &file_api_server_v1_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerBasic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerBasic) ProtoMessage() {}

func (x *ServerBasic) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerBasic.ProtoReflect.Descriptor instead.
func (*ServerBasic) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{6}
}

func (x *ServerBasic) GetPushInterval() int64 {
	if x != nil {
		return x.PushInterval
	}
	return 0
}

func (x *ServerBasic) GetPullInterval() int64 {
	if x != nil {
		return x.PullInterval
	}
	return 0
}

// Config is intentionally dynamic because the fields depend on the selected
// node protocol. It has the same object shape as the JSON config property.
type ServerConfigData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Basic         *ServerBasic           `protobuf:"bytes,1,opt,name=basic,proto3" json:"basic,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfigData) Reset() {
	*x = ServerConfigData{}
	mi := &file_api_server_v1_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfigData) ProtoMessage() {}

func (x *ServerConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfigData.ProtoReflect.Descriptor instead.
func (*ServerConfigData) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{7}
}

func (x *ServerConfigData) GetBasic() *ServerBasic {
	if x != nil {
		return x.Basic
	}
	return nil
}

func (x *ServerConfigData) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServerConfigData) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetServerConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ServerConfigData      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerConfigResponse) Reset() {
	*x = GetServerConfigResponse{}
	mi := &file_api_server_v1_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerConfigResponse) ProtoMessage() {}

func (x *GetServerConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerConfigResponse.ProtoReflect.Descriptor instead.
func (*GetServerConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetServerConfigResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetServerConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServerConfigResponse) GetData() *ServerConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ServerUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SpeedLimit    int64                  `protobuf:"varint,3,opt,name=speed_limit,json=speedLimit,proto3" json:"speed_limit,omitempty"`
	DeviceLimit   int64                  `protobuf:"varint,4,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUser) Reset() {
	*x = ServerUser{}
	mi := &file_api_server_v1_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUser) ProtoMessage() {}

func (x *ServerUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUser.ProtoReflect.Descriptor instead.
func (*ServerUser) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{9}
}

func (x *ServerUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServerUser) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ServerUser) GetSpeedLimit() int64 {
	if x != nil {
		return x.SpeedLimit
	}
	return 0
}

func (x *ServerUser) GetDeviceLimit() int64 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

type ServerUserListData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ServerUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerUserListData) Reset() {
	*x = ServerUserListData{}
	mi := &file_api_server_v1_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerUserListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerUserListData) ProtoMessage() {}

func (x *ServerUserListData) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerUserListData.ProtoReflect.Descriptor instead.
func (*ServerUserListData) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{10}
}

func (x *ServerUserListData) GetUsers() []*ServerUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetServerUserListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ServerUserListData    `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerUserListResponse) Reset() {
	*x = GetServerUserListResponse{}
	mi := &file_api_server_v1_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerUserListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerUserListResponse) ProtoMessage() {}

func (x *GetServerUserListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerUserListResponse.ProtoReflect.Descriptor instead.
func (*GetServerUserListResponse) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{11}
}

func (x *GetServerUserListResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetServerUserListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServerUserListResponse) GetData() *ServerUserListData {
	if x != nil {
		return x.Data
	}
	return nil
}

// DNSResolver is one DNS resolver used by the node runtime.
type DNSResolver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Domains       []string               `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSResolver) Reset() {
	*x = DNSResolver{}
	mi := &file_api_server_v1_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSResolver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSResolver) ProtoMessage() {}

func (x *DNSResolver) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSResolver.ProtoReflect.Descriptor instead.
func (*DNSResolver) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{12}
}

func (x *DNSResolver) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *DNSResolver) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DNSResolver) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *DNSResolver) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Outbound is one normalized outbound configuration. plugin_options preserves
// both object and SIP003 string forms accepted by the existing JSON API.
type Outbound struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol                string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Address                 string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port                    int64                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	User                    string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Password                string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Uuid                    string                 `protobuf:"bytes,7,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cipher                  string                 `protobuf:"bytes,8,opt,name=cipher,proto3" json:"cipher,omitempty"`
	Plugin                  string                 `protobuf:"bytes,9,opt,name=plugin,proto3" json:"plugin,omitempty"`
	PluginOptions           *structpb.Value        `protobuf:"bytes,10,opt,name=plugin_options,json=pluginOptions,proto3" json:"plugin_options,omitempty"`
	Security                string                 `protobuf:"bytes,11,opt,name=security,proto3" json:"security,omitempty"`
	Sni                     string                 `protobuf:"bytes,12,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn                    []string               `protobuf:"bytes,13,rep,name=alpn,proto3" json:"alpn,omitempty"`
	AllowInsecure           bool                   `protobuf:"varint,14,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	Fingerprint             string                 `protobuf:"bytes,15,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Transport               string                 `protobuf:"bytes,16,opt,name=transport,proto3" json:"transport,omitempty"`
	Host                    string                 `protobuf:"bytes,17,opt,name=host,proto3" json:"host,omitempty"`
	Path                    string                 `protobuf:"bytes,18,opt,name=path,proto3" json:"path,omitempty"`
	ServiceName             string                 `protobuf:"bytes,19,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XhttpMode               string                 `protobuf:"bytes,20,opt,name=xhttp_mode,json=xhttpMode,proto3" json:"xhttp_mode,omitempty"`
	XhttpExtra              string                 `protobuf:"bytes,21,opt,name=xhttp_extra,json=xhttpExtra,proto3" json:"xhttp_extra,omitempty"`
	Flow                    string                 `protobuf:"bytes,22,opt,name=flow,proto3" json:"flow,omitempty"`
	Encryption              string                 `protobuf:"bytes,23,opt,name=encryption,proto3" json:"encryption,omitempty"`
	EncryptionMode          string                 `protobuf:"bytes,24,opt,name=encryption_mode,json=encryptionMode,proto3" json:"encryption_mode,omitempty"`
	EncryptionRtt           string                 `protobuf:"bytes,25,opt,name=encryption_rtt,json=encryptionRtt,proto3" json:"encryption_rtt,omitempty"`
	EncryptionTicket        string                 `protobuf:"bytes,26,opt,name=encryption_ticket,json=encryptionTicket,proto3" json:"encryption_ticket,omitempty"`
	EncryptionClientPadding string                 `protobuf:"bytes,27,opt,name=encryption_client_padding,json=encryptionClientPadding,proto3" json:"encryption_client_padding,omitempty"`
	EncryptionPassword      string                 `protobuf:"bytes,28,opt,name=encryption_password,json=encryptionPassword,proto3" json:"encryption_password,omitempty"`
	Multiplex               string                 `protobuf:"bytes,29,opt,name=multiplex,proto3" json:"multiplex,omitempty"`
	Uot                     bool                   `protobuf:"varint,30,opt,name=uot,proto3" json:"uot,omitempty"`
	UotVersion              int64                  `protobuf:"varint,31,opt,name=uot_version,json=uotVersion,proto3" json:"uot_version,omitempty"`
	CongestionController    string                 `protobuf:"bytes,32,opt,name=congestion_controller,json=congestionController,proto3" json:"congestion_controller,omitempty"`
	UdpStream               bool                   `protobuf:"varint,33,opt,name=udp_stream,json=udpStream,proto3" json:"udp_stream,omitempty"`
	ReduceRtt               bool                   `protobuf:"varint,34,opt,name=reduce_rtt,json=reduceRtt,proto3" json:"reduce_rtt,omitempty"`
	Heartbeat               int64                  `protobuf:"varint,35,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	RealityPublicKey        string                 `protobuf:"bytes,36,opt,name=reality_public_key,json=realityPublicKey,proto3" json:"reality_public_key,omitempty"`
	RealityShortId          string                 `protobuf:"bytes,37,opt,name=reality_short_id,json=realityShortId,proto3" json:"reality_short_id,omitempty"`
	SpiderX                 string                 `protobuf:"bytes,38,opt,name=spider_x,json=spiderX,proto3" json:"spider_x,omitempty"`
	Settings                string                 `protobuf:"bytes,39,opt,name=settings,proto3" json:"settings,omitempty"`
	StreamSettings          string                 `protobuf:"bytes,40,opt,name=stream_settings,json=streamSettings,proto3" json:"stream_settings,omitempty"`
	Rules                   []string               `protobuf:"bytes,41,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Outbound) Reset() {
	*x = Outbound{}
	mi := &file_api_server_v1_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outbound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outbound) ProtoMessage() {}

func (x *Outbound) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outbound.ProtoReflect.Descriptor instead.
func (*Outbound) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{13}
}

func (x *Outbound) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Outbound) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Outbound) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Outbound) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Outbound) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Outbound) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Outbound) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Outbound) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *Outbound) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *Outbound) GetPluginOptions() *structpb.Value {
	if x != nil {
		return x.PluginOptions
	}
	return nil
}

func (x *Outbound) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *Outbound) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *Outbound) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *Outbound) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *Outbound) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *Outbound) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Outbound) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Outbound) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Outbound) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Outbound) GetXhttpMode() string {
	if x != nil {
		return x.XhttpMode
	}
	return ""
}

func (x *Outbound) GetXhttpExtra() string {
	if x != nil {
		return x.XhttpExtra
	}
	return ""
}

func (x *Outbound) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *Outbound) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *Outbound) GetEncryptionMode() string {
	if x != nil {
		return x.EncryptionMode
	}
	return ""
}

func (x *Outbound) GetEncryptionRtt() string {
	if x != nil {
		return x.EncryptionRtt
	}
	return ""
}

func (x *Outbound) GetEncryptionTicket() string {
	if x != nil {
		return x.EncryptionTicket
	}
	return ""
}

func (x *Outbound) GetEncryptionClientPadding() string {
	if x != nil {
		return x.EncryptionClientPadding
	}
	return ""
}

func (x *Outbound) GetEncryptionPassword() string {
	if x != nil {
		return x.EncryptionPassword
	}
	return ""
}

func (x *Outbound) GetMultiplex() string {
	if x != nil {
		return x.Multiplex
	}
	return ""
}

func (x *Outbound) GetUot() bool {
	if x != nil {
		return x.Uot
	}
	return false
}

func (x *Outbound) GetUotVersion() int64 {
	if x != nil {
		return x.UotVersion
	}
	return 0
}

func (x *Outbound) GetCongestionController() string {
	if x != nil {
		return x.CongestionController
	}
	return ""
}

func (x *Outbound) GetUdpStream() bool {
	if x != nil {
		return x.UdpStream
	}
	return false
}

func (x *Outbound) GetReduceRtt() bool {
	if x != nil {
		return x.ReduceRtt
	}
	return false
}

func (x *Outbound) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *Outbound) GetRealityPublicKey() string {
	if x != nil {
		return x.RealityPublicKey
	}
	return ""
}

func (x *Outbound) GetRealityShortId() string {
	if x != nil {
		return x.RealityShortId
	}
	return ""
}

func (x *Outbound) GetSpiderX() string {
	if x != nil {
		return x.SpiderX
	}
	return ""
}

func (x *Outbound) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *Outbound) GetStreamSettings() string {
	if x != nil {
		return x.StreamSettings
	}
	return ""
}

func (x *Outbound) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

// ServerProtocol is PPanel's normalized, flat protocol configuration. The
// protocol type identifies which fields are consumed by a node runtime; a flat
// model matches the established PPanel and Star-Node integration contract.
type ServerProtocol struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Type                    string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Port                    uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Version                 int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Mode                    string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Enable                  bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	Security                string                 `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"`
	Network                 string                 `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`
	Sni                     string                 `protobuf:"bytes,8,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn                    []string               `protobuf:"bytes,9,rep,name=alpn,proto3" json:"alpn,omitempty"`
	AllowInsecure           bool                   `protobuf:"varint,10,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	Fingerprint             string                 `protobuf:"bytes,11,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	RealityServerAddr       string                 `protobuf:"bytes,12,opt,name=reality_server_addr,json=realityServerAddr,proto3" json:"reality_server_addr,omitempty"`
	RealityServerPort       int64                  `protobuf:"varint,13,opt,name=reality_server_port,json=realityServerPort,proto3" json:"reality_server_port,omitempty"`
	RealityPrivateKey       string                 `protobuf:"bytes,14,opt,name=reality_private_key,json=realityPrivateKey,proto3" json:"reality_private_key,omitempty"`
	RealityPublicKey        string                 `protobuf:"bytes,15,opt,name=reality_public_key,json=realityPublicKey,proto3" json:"reality_public_key,omitempty"`
	RealityShortId          string                 `protobuf:"bytes,16,opt,name=reality_short_id,json=realityShortId,proto3" json:"reality_short_id,omitempty"`
	Transport               string                 `protobuf:"bytes,17,opt,name=transport,proto3" json:"transport,omitempty"`
	Host                    string                 `protobuf:"bytes,18,opt,name=host,proto3" json:"host,omitempty"`
	Path                    string                 `protobuf:"bytes,19,opt,name=path,proto3" json:"path,omitempty"`
	ServiceName             string                 `protobuf:"bytes,20,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Cipher                  string                 `protobuf:"bytes,21,opt,name=cipher,proto3" json:"cipher,omitempty"`
	ServerKey               string                 `protobuf:"bytes,22,opt,name=server_key,json=serverKey,proto3" json:"server_key,omitempty"`
	Plugin                  string                 `protobuf:"bytes,23,opt,name=plugin,proto3" json:"plugin,omitempty"`
	PluginOptions           *structpb.Value        `protobuf:"bytes,24,opt,name=plugin_options,json=pluginOptions,proto3" json:"plugin_options,omitempty"`
	Flow                    string                 `protobuf:"bytes,25,opt,name=flow,proto3" json:"flow,omitempty"`
	Uot                     bool                   `protobuf:"varint,26,opt,name=uot,proto3" json:"uot,omitempty"`
	UotVersion              int64                  `protobuf:"varint,27,opt,name=uot_version,json=uotVersion,proto3" json:"uot_version,omitempty"`
	AcceptProxyProtocol     bool                   `protobuf:"varint,28,opt,name=accept_proxy_protocol,json=acceptProxyProtocol,proto3" json:"accept_proxy_protocol,omitempty"`
	HopPorts                string                 `protobuf:"bytes,29,opt,name=hop_ports,json=hopPorts,proto3" json:"hop_ports,omitempty"`
	HopInterval             int64                  `protobuf:"varint,30,opt,name=hop_interval,json=hopInterval,proto3" json:"hop_interval,omitempty"`
	ObfsPassword            string                 `protobuf:"bytes,31,opt,name=obfs_password,json=obfsPassword,proto3" json:"obfs_password,omitempty"`
	DisableSni              bool                   `protobuf:"varint,32,opt,name=disable_sni,json=disableSni,proto3" json:"disable_sni,omitempty"`
	ReduceRtt               bool                   `protobuf:"varint,33,opt,name=reduce_rtt,json=reduceRtt,proto3" json:"reduce_rtt,omitempty"`
	Heartbeat               int64                  `protobuf:"varint,34,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	UdpRelayMode            string                 `protobuf:"bytes,35,opt,name=udp_relay_mode,json=udpRelayMode,proto3" json:"udp_relay_mode,omitempty"`
	CongestionController    string                 `protobuf:"bytes,36,opt,name=congestion_controller,json=congestionController,proto3" json:"congestion_controller,omitempty"`
	QuicCongestionControl   string                 `protobuf:"bytes,37,opt,name=quic_congestion_control,json=quicCongestionControl,proto3" json:"quic_congestion_control,omitempty"`
	Multiplex               string                 `protobuf:"bytes,38,opt,name=multiplex,proto3" json:"multiplex,omitempty"`
	PaddingScheme           string                 `protobuf:"bytes,39,opt,name=padding_scheme,json=paddingScheme,proto3" json:"padding_scheme,omitempty"`
	TrafficPattern          string                 `protobuf:"bytes,40,opt,name=traffic_pattern,json=trafficPattern,proto3" json:"traffic_pattern,omitempty"`
	UserHintIsMandatory     bool                   `protobuf:"varint,41,opt,name=user_hint_is_mandatory,json=userHintIsMandatory,proto3" json:"user_hint_is_mandatory,omitempty"`
	UpMbps                  int64                  `protobuf:"varint,42,opt,name=up_mbps,json=upMbps,proto3" json:"up_mbps,omitempty"`
	DownMbps                int64                  `protobuf:"varint,43,opt,name=down_mbps,json=downMbps,proto3" json:"down_mbps,omitempty"`
	Obfs                    string                 `protobuf:"bytes,44,opt,name=obfs,proto3" json:"obfs,omitempty"`
	SsrProtocol             string                 `protobuf:"bytes,45,opt,name=ssr_protocol,json=ssrProtocol,proto3" json:"ssr_protocol,omitempty"`
	ProtocolParam           string                 `protobuf:"bytes,46,opt,name=protocol_param,json=protocolParam,proto3" json:"protocol_param,omitempty"`
	ObfsParam               string                 `protobuf:"bytes,47,opt,name=obfs_param,json=obfsParam,proto3" json:"obfs_param,omitempty"`
	ObfsHost                string                 `protobuf:"bytes,48,opt,name=obfs_host,json=obfsHost,proto3" json:"obfs_host,omitempty"`
	ObfsPath                string                 `protobuf:"bytes,49,opt,name=obfs_path,json=obfsPath,proto3" json:"obfs_path,omitempty"`
	XhttpMode               string                 `protobuf:"bytes,50,opt,name=xhttp_mode,json=xhttpMode,proto3" json:"xhttp_mode,omitempty"`
	XhttpExtra              string                 `protobuf:"bytes,51,opt,name=xhttp_extra,json=xhttpExtra,proto3" json:"xhttp_extra,omitempty"`
	Encryption              string                 `protobuf:"bytes,52,opt,name=encryption,proto3" json:"encryption,omitempty"`
	EncryptionMode          string                 `protobuf:"bytes,53,opt,name=encryption_mode,json=encryptionMode,proto3" json:"encryption_mode,omitempty"`
	EncryptionRtt           string                 `protobuf:"bytes,54,opt,name=encryption_rtt,json=encryptionRtt,proto3" json:"encryption_rtt,omitempty"`
	EncryptionTicket        string                 `protobuf:"bytes,55,opt,name=encryption_ticket,json=encryptionTicket,proto3" json:"encryption_ticket,omitempty"`
	EncryptionServerPadding string                 `protobuf:"bytes,56,opt,name=encryption_server_padding,json=encryptionServerPadding,proto3" json:"encryption_server_padding,omitempty"`
	EncryptionPrivateKey    string                 `protobuf:"bytes,57,opt,name=encryption_private_key,json=encryptionPrivateKey,proto3" json:"encryption_private_key,omitempty"`
	EncryptionClientPadding string                 `protobuf:"bytes,58,opt,name=encryption_client_padding,json=encryptionClientPadding,proto3" json:"encryption_client_padding,omitempty"`
	EncryptionPassword      string                 `protobuf:"bytes,59,opt,name=encryption_password,json=encryptionPassword,proto3" json:"encryption_password,omitempty"`
	EchEnable               bool                   `protobuf:"varint,60,opt,name=ech_enable,json=echEnable,proto3" json:"ech_enable,omitempty"`
	EchServerName           string                 `protobuf:"bytes,61,opt,name=ech_server_name,json=echServerName,proto3" json:"ech_server_name,omitempty"`
	Ratio                   float64                `protobuf:"fixed64,62,opt,name=ratio,proto3" json:"ratio,omitempty"`
	CertMode                string                 `protobuf:"bytes,63,opt,name=cert_mode,json=certMode,proto3" json:"cert_mode,omitempty"`
	CertDnsProvider         string                 `protobuf:"bytes,64,opt,name=cert_dns_provider,json=certDnsProvider,proto3" json:"cert_dns_provider,omitempty"`
	CertDnsEnv              string                 `protobuf:"bytes,65,opt,name=cert_dns_env,json=certDnsEnv,proto3" json:"cert_dns_env,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ServerProtocol) Reset() {
	*x = ServerProtocol{}
	mi := &file_api_server_v1_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProtocol) ProtoMessage() {}

func (x *ServerProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProtocol.ProtoReflect.Descriptor instead.
func (*ServerProtocol) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{14}
}

func (x *ServerProtocol) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerProtocol) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerProtocol) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ServerProtocol) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ServerProtocol) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ServerProtocol) GetSecurity() string {
	if x != nil {
		return x.Security
	}
	return ""
}

func (x *ServerProtocol) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ServerProtocol) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ServerProtocol) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *ServerProtocol) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *ServerProtocol) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *ServerProtocol) GetRealityServerAddr() string {
	if x != nil {
		return x.RealityServerAddr
	}
	return ""
}

func (x *ServerProtocol) GetRealityServerPort() int64 {
	if x != nil {
		return x.RealityServerPort
	}
	return 0
}

func (x *ServerProtocol) GetRealityPrivateKey() string {
	if x != nil {
		return x.RealityPrivateKey
	}
	return ""
}

func (x *ServerProtocol) GetRealityPublicKey() string {
	if x != nil {
		return x.RealityPublicKey
	}
	return ""
}

func (x *ServerProtocol) GetRealityShortId() string {
	if x != nil {
		return x.RealityShortId
	}
	return ""
}

func (x *ServerProtocol) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServerProtocol) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerProtocol) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ServerProtocol) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServerProtocol) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *ServerProtocol) GetServerKey() string {
	if x != nil {
		return x.ServerKey
	}
	return ""
}

func (x *ServerProtocol) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ServerProtocol) GetPluginOptions() *structpb.Value {
	if x != nil {
		return x.PluginOptions
	}
	return nil
}

func (x *ServerProtocol) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *ServerProtocol) GetUot() bool {
	if x != nil {
		return x.Uot
	}
	return false
}

func (x *ServerProtocol) GetUotVersion() int64 {
	if x != nil {
		return x.UotVersion
	}
	return 0
}

func (x *ServerProtocol) GetAcceptProxyProtocol() bool {
	if x != nil {
		return x.AcceptProxyProtocol
	}
	return false
}

func (x *ServerProtocol) GetHopPorts() string {
	if x != nil {
		return x.HopPorts
	}
	return ""
}

func (x *ServerProtocol) GetHopInterval() int64 {
	if x != nil {
		return x.HopInterval
	}
	return 0
}

func (x *ServerProtocol) GetObfsPassword() string {
	if x != nil {
		return x.ObfsPassword
	}
	return ""
}

func (x *ServerProtocol) GetDisableSni() bool {
	if x != nil {
		return x.DisableSni
	}
	return false
}

func (x *ServerProtocol) GetReduceRtt() bool {
	if x != nil {
		return x.ReduceRtt
	}
	return false
}

func (x *ServerProtocol) GetHeartbeat() int64 {
	if x != nil {
		return x.Heartbeat
	}
	return 0
}

func (x *ServerProtocol) GetUdpRelayMode() string {
	if x != nil {
		return x.UdpRelayMode
	}
	return ""
}

func (x *ServerProtocol) GetCongestionController() string {
	if x != nil {
		return x.CongestionController
	}
	return ""
}

func (x *ServerProtocol) GetQuicCongestionControl() string {
	if x != nil {
		return x.QuicCongestionControl
	}
	return ""
}

func (x *ServerProtocol) GetMultiplex() string {
	if x != nil {
		return x.Multiplex
	}
	return ""
}

func (x *ServerProtocol) GetPaddingScheme() string {
	if x != nil {
		return x.PaddingScheme
	}
	return ""
}

func (x *ServerProtocol) GetTrafficPattern() string {
	if x != nil {
		return x.TrafficPattern
	}
	return ""
}

func (x *ServerProtocol) GetUserHintIsMandatory() bool {
	if x != nil {
		return x.UserHintIsMandatory
	}
	return false
}

func (x *ServerProtocol) GetUpMbps() int64 {
	if x != nil {
		return x.UpMbps
	}
	return 0
}

func (x *ServerProtocol) GetDownMbps() int64 {
	if x != nil {
		return x.DownMbps
	}
	return 0
}

func (x *ServerProtocol) GetObfs() string {
	if x != nil {
		return x.Obfs
	}
	return ""
}

func (x *ServerProtocol) GetSsrProtocol() string {
	if x != nil {
		return x.SsrProtocol
	}
	return ""
}

func (x *ServerProtocol) GetProtocolParam() string {
	if x != nil {
		return x.ProtocolParam
	}
	return ""
}

func (x *ServerProtocol) GetObfsParam() string {
	if x != nil {
		return x.ObfsParam
	}
	return ""
}

func (x *ServerProtocol) GetObfsHost() string {
	if x != nil {
		return x.ObfsHost
	}
	return ""
}

func (x *ServerProtocol) GetObfsPath() string {
	if x != nil {
		return x.ObfsPath
	}
	return ""
}

func (x *ServerProtocol) GetXhttpMode() string {
	if x != nil {
		return x.XhttpMode
	}
	return ""
}

func (x *ServerProtocol) GetXhttpExtra() string {
	if x != nil {
		return x.XhttpExtra
	}
	return ""
}

func (x *ServerProtocol) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionMode() string {
	if x != nil {
		return x.EncryptionMode
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionRtt() string {
	if x != nil {
		return x.EncryptionRtt
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionTicket() string {
	if x != nil {
		return x.EncryptionTicket
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionServerPadding() string {
	if x != nil {
		return x.EncryptionServerPadding
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionPrivateKey() string {
	if x != nil {
		return x.EncryptionPrivateKey
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionClientPadding() string {
	if x != nil {
		return x.EncryptionClientPadding
	}
	return ""
}

func (x *ServerProtocol) GetEncryptionPassword() string {
	if x != nil {
		return x.EncryptionPassword
	}
	return ""
}

func (x *ServerProtocol) GetEchEnable() bool {
	if x != nil {
		return x.EchEnable
	}
	return false
}

func (x *ServerProtocol) GetEchServerName() string {
	if x != nil {
		return x.EchServerName
	}
	return ""
}

func (x *ServerProtocol) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *ServerProtocol) GetCertMode() string {
	if x != nil {
		return x.CertMode
	}
	return ""
}

func (x *ServerProtocol) GetCertDnsProvider() string {
	if x != nil {
		return x.CertDnsProvider
	}
	return ""
}

func (x *ServerProtocol) GetCertDnsEnv() string {
	if x != nil {
		return x.CertDnsEnv
	}
	return ""
}

// QueryServerProtocolConfigData is the strongly typed data payload returned
// by GET /v2/server/{server_id}.
type QueryServerProtocolConfigData struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TrafficReportThreshold int64                  `protobuf:"varint,1,opt,name=traffic_report_threshold,json=trafficReportThreshold,proto3" json:"traffic_report_threshold,omitempty"`
	PushInterval           int64                  `protobuf:"varint,2,opt,name=push_interval,json=pushInterval,proto3" json:"push_interval,omitempty"`
	PullInterval           int64                  `protobuf:"varint,3,opt,name=pull_interval,json=pullInterval,proto3" json:"pull_interval,omitempty"`
	IpStrategy             string                 `protobuf:"bytes,4,opt,name=ip_strategy,json=ipStrategy,proto3" json:"ip_strategy,omitempty"`
	Dns                    []*DNSResolver         `protobuf:"bytes,5,rep,name=dns,proto3" json:"dns,omitempty"`
	Block                  []string               `protobuf:"bytes,6,rep,name=block,proto3" json:"block,omitempty"`
	Outbound               []*Outbound            `protobuf:"bytes,7,rep,name=outbound,proto3" json:"outbound,omitempty"`
	Protocols              []*ServerProtocol      `protobuf:"bytes,8,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Total                  int64                  `protobuf:"varint,9,opt,name=total,proto3" json:"total,omitempty"`
	// target_version 是控制台希望该节点运行的版本，空串表示不干预。
	// 【必须同时存在于 JSON 和 protobuf 两条路径】节点拉配置时无条件请求
	// protobuf，只加 JSON 字段的话它永远读不到，而且不会报错。
	// 【字段号必须和另一个仓库一致】见本文件顶部关于 wire 兼容的说明。
	TargetVersion string `protobuf:"bytes,10,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryServerProtocolConfigData) Reset() {
	*x = QueryServerProtocolConfigData{}
	mi := &file_api_server_v1_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryServerProtocolConfigData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServerProtocolConfigData) ProtoMessage() {}

func (x *QueryServerProtocolConfigData) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServerProtocolConfigData.ProtoReflect.Descriptor instead.
func (*QueryServerProtocolConfigData) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{15}
}

func (x *QueryServerProtocolConfigData) GetTrafficReportThreshold() int64 {
	if x != nil {
		return x.TrafficReportThreshold
	}
	return 0
}

func (x *QueryServerProtocolConfigData) GetPushInterval() int64 {
	if x != nil {
		return x.PushInterval
	}
	return 0
}

func (x *QueryServerProtocolConfigData) GetPullInterval() int64 {
	if x != nil {
		return x.PullInterval
	}
	return 0
}

func (x *QueryServerProtocolConfigData) GetIpStrategy() string {
	if x != nil {
		return x.IpStrategy
	}
	return ""
}

func (x *QueryServerProtocolConfigData) GetDns() []*DNSResolver {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *QueryServerProtocolConfigData) GetBlock() []string {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *QueryServerProtocolConfigData) GetOutbound() []*Outbound {
	if x != nil {
		return x.Outbound
	}
	return nil
}

func (x *QueryServerProtocolConfigData) GetProtocols() []*ServerProtocol {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *QueryServerProtocolConfigData) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryServerProtocolConfigData) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type QueryServerProtocolConfigResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          uint32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *QueryServerProtocolConfigData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryServerProtocolConfigResponse) Reset() {
	*x = QueryServerProtocolConfigResponse{}
	mi := &file_api_server_v1_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryServerProtocolConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryServerProtocolConfigResponse) ProtoMessage() {}

func (x *QueryServerProtocolConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_v1_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryServerProtocolConfigResponse.ProtoReflect.Descriptor instead.
func (*QueryServerProtocolConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_server_v1_server_proto_rawDescGZIP(), []int{16}
}

func (x *QueryServerProtocolConfigResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *QueryServerProtocolConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueryServerProtocolConfigResponse) GetData() *QueryServerProtocolConfigData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_api_server_v1_server_proto protoreflect.FileDescriptor

const file_api_server_v1_server_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/server/v1/server.proto\x12\x10ppanel.server.v1\x1a\x1cgoogle/protobuf/struct.proto\"5\n" +
	"\n" +
	"OnlineUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"L\n" +
	"\x16PushOnlineUsersRequest\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.ppanel.server.v1.OnlineUserR\x05users\"Z\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06upload\x18\x02 \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\x03 \x01(\x03R\bdownload\"Q\n" +
	"\x16PushUserTrafficRequest\x127\n" +
	"\atraffic\x18\x01 \x03(\v2\x1d.ppanel.server.v1.UserTrafficR\atraffic\"\xb1\x01\n" +
	"\x17PushServerStatusRequest\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x02 \x01(\x01R\x03mem\x12\x12\n" +
	"\x04disk\x18\x03 \x01(\x01R\x04disk\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12%\n" +
	"\x0elatest_version\x18\x06 \x01(\tR\rlatestVersion\"6\n" +
	"\x06Result\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"W\n" +
	"\vServerBasic\x12#\n" +
	"\rpush_interval\x18\x01 \x01(\x03R\fpushInterval\x12#\n" +
	"\rpull_interval\x18\x02 \x01(\x03R\fpullInterval\"\x94\x01\n" +
	"\x10ServerConfigData\x123\n" +
	"\x05basic\x18\x01 \x01(\v2\x1d.ppanel.server.v1.ServerBasicR\x05basic\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x7f\n" +
	"\x17GetServerConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".ppanel.server.v1.ServerConfigDataR\x04data\"t\n" +
	"\n" +
	"ServerUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vspeed_limit\x18\x03 \x01(\x03R\n" +
	"speedLimit\x12!\n" +
	"\fdevice_limit\x18\x04 \x01(\x03R\vdeviceLimit\"H\n" +
	"\x12ServerUserListData\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.ppanel.server.v1.ServerUserR\x05users\"\x83\x01\n" +
	"\x19GetServerUserListResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\x04data\x18\x03 \x01(\v2$.ppanel.server.v1.ServerUserListDataR\x04data\"x\n" +
	"\vDNSResolver\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\adomains\x18\x04 \x03(\tR\adomains\"\x9d\n" +
	"\n" +
	"\bOutbound\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x03R\x04port\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x12\n" +
	"\x04uuid\x18\a \x01(\tR\x04uuid\x12\x16\n" +
	"\x06cipher\x18\b \x01(\tR\x06cipher\x12\x16\n" +
	"\x06plugin\x18\t \x01(\tR\x06plugin\x12=\n" +
	"\x0eplugin_options\x18\n" +
	" \x01(\v2\x16.google.protobuf.ValueR\rpluginOptions\x12\x1a\n" +
	"\bsecurity\x18\v \x01(\tR\bsecurity\x12\x10\n" +
	"\x03sni\x18\f \x01(\tR\x03sni\x12\x12\n" +
	"\x04alpn\x18\r \x03(\tR\x04alpn\x12%\n" +
	"\x0eallow_insecure\x18\x0e \x01(\bR\rallowInsecure\x12 \n" +
	"\vfingerprint\x18\x0f \x01(\tR\vfingerprint\x12\x1c\n" +
	"\ttransport\x18\x10 \x01(\tR\ttransport\x12\x12\n" +
	"\x04host\x18\x11 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x12 \x01(\tR\x04path\x12!\n" +
	"\fservice_name\x18\x13 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"xhttp_mode\x18\x14 \x01(\tR\txhttpMode\x12\x1f\n" +
	"\vxhttp_extra\x18\x15 \x01(\tR\n" +
	"xhttpExtra\x12\x12\n" +
	"\x04flow\x18\x16 \x01(\tR\x04flow\x12\x1e\n" +
	"\n" +
	"encryption\x18\x17 \x01(\tR\n" +
	"encryption\x12'\n" +
	"\x0fencryption_mode\x18\x18 \x01(\tR\x0eencryptionMode\x12%\n" +
	"\x0eencryption_rtt\x18\x19 \x01(\tR\rencryptionRtt\x12+\n" +
	"\x11encryption_ticket\x18\x1a \x01(\tR\x10encryptionTicket\x12:\n" +
	"\x19encryption_client_padding\x18\x1b \x01(\tR\x17encryptionClientPadding\x12/\n" +
	"\x13encryption_password\x18\x1c \x01(\tR\x12encryptionPassword\x12\x1c\n" +
	"\tmultiplex\x18\x1d \x01(\tR\tmultiplex\x12\x10\n" +
	"\x03uot\x18\x1e \x01(\bR\x03uot\x12\x1f\n" +
	"\vuot_version\x18\x1f \x01(\x03R\n" +
	"uotVersion\x123\n" +
	"\x15congestion_controller\x18  \x01(\tR\x14congestionController\x12\x1d\n" +
	"\n" +
	"udp_stream\x18! \x01(\bR\tudpStream\x12\x1d\n" +
	"\n" +
	"reduce_rtt\x18\" \x01(\bR\treduceRtt\x12\x1c\n" +
	"\theartbeat\x18# \x01(\x03R\theartbeat\x12,\n" +
	"\x12reality_public_key\x18$ \x01(\tR\x10realityPublicKey\x12(\n" +
	"\x10reality_short_id\x18% \x01(\tR\x0erealityShortId\x12\x19\n" +
	"\bspider_x\x18& \x01(\tR\aspiderX\x12\x1a\n" +
	"\bsettings\x18' \x01(\tR\bsettings\x12'\n" +
	"\x0fstream_settings\x18( \x01(\tR\x0estreamSettings\x12\x14\n" +
	"\x05rules\x18) \x03(\tR\x05rules\"\xe7\x11\n" +
	"\x0eServerProtocol\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enable\x12\x1a\n" +
	"\bsecurity\x18\x06 \x01(\tR\bsecurity\x12\x18\n" +
	"\anetwork\x18\a \x01(\tR\anetwork\x12\x10\n" +
	"\x03sni\x18\b \x01(\tR\x03sni\x12\x12\n" +
	"\x04alpn\x18\t \x03(\tR\x04alpn\x12%\n" +
	"\x0eallow_insecure\x18\n" +
	" \x01(\bR\rallowInsecure\x12 \n" +
	"\vfingerprint\x18\v \x01(\tR\vfingerprint\x12.\n" +
	"\x13reality_server_addr\x18\f \x01(\tR\x11realityServerAddr\x12.\n" +
	"\x13reality_server_port\x18\r \x01(\x03R\x11realityServerPort\x12.\n" +
	"\x13reality_private_key\x18\x0e \x01(\tR\x11realityPrivateKey\x12,\n" +
	"\x12reality_public_key\x18\x0f \x01(\tR\x10realityPublicKey\x12(\n" +
	"\x10reality_short_id\x18\x10 \x01(\tR\x0erealityShortId\x12\x1c\n" +
	"\ttransport\x18\x11 \x01(\tR\ttransport\x12\x12\n" +
	"\x04host\x18\x12 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x13 \x01(\tR\x04path\x12!\n" +
	"\fservice_name\x18\x14 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06cipher\x18\x15 \x01(\tR\x06cipher\x12\x1d\n" +
	"\n" +
	"server_key\x18\x16 \x01(\tR\tserverKey\x12\x16\n" +
	"\x06plugin\x18\x17 \x01(\tR\x06plugin\x12=\n" +
	"\x0eplugin_options\x18\x18 \x01(\v2\x16.google.protobuf.ValueR\rpluginOptions\x12\x12\n" +
	"\x04flow\x18\x19 \x01(\tR\x04flow\x12\x10\n" +
	"\x03uot\x18\x1a \x01(\bR\x03uot\x12\x1f\n" +
	"\vuot_version\x18\x1b \x01(\x03R\n" +
	"uotVersion\x122\n" +
	"\x15accept_proxy_protocol\x18\x1c \x01(\bR\x13acceptProxyProtocol\x12\x1b\n" +
	"\thop_ports\x18\x1d \x01(\tR\bhopPorts\x12!\n" +
	"\fhop_interval\x18\x1e \x01(\x03R\vhopInterval\x12#\n" +
	"\robfs_password\x18\x1f \x01(\tR\fobfsPassword\x12\x1f\n" +
	"\vdisable_sni\x18  \x01(\bR\n" +
	"disableSni\x12\x1d\n" +
	"\n" +
	"reduce_rtt\x18! \x01(\bR\treduceRtt\x12\x1c\n" +
	"\theartbeat\x18\" \x01(\x03R\theartbeat\x12$\n" +
	"\x0eudp_relay_mode\x18# \x01(\tR\fudpRelayMode\x123\n" +
	"\x15congestion_controller\x18$ \x01(\tR\x14congestionController\x126\n" +
	"\x17quic_congestion_control\x18% \x01(\tR\x15quicCongestionControl\x12\x1c\n" +
	"\tmultiplex\x18& \x01(\tR\tmultiplex\x12%\n" +
	"\x0epadding_scheme\x18' \x01(\tR\rpaddingScheme\x12'\n" +
	"\x0ftraffic_pattern\x18( \x01(\tR\x0etrafficPattern\x123\n" +
	"\x16user_hint_is_mandatory\x18) \x01(\bR\x13userHintIsMandatory\x12\x17\n" +
	"\aup_mbps\x18* \x01(\x03R\x06upMbps\x12\x1b\n" +
	"\tdown_mbps\x18+ \x01(\x03R\bdownMbps\x12\x12\n" +
	"\x04obfs\x18, \x01(\tR\x04obfs\x12!\n" +
	"\fssr_protocol\x18- \x01(\tR\vssrProtocol\x12%\n" +
	"\x0eprotocol_param\x18. \x01(\tR\rprotocolParam\x12\x1d\n" +
	"\n" +
	"obfs_param\x18/ \x01(\tR\tobfsParam\x12\x1b\n" +
	"\tobfs_host\x180 \x01(\tR\bobfsHost\x12\x1b\n" +
	"\tobfs_path\x181 \x01(\tR\bobfsPath\x12\x1d\n" +
	"\n" +
	"xhttp_mode\x182 \x01(\tR\txhttpMode\x12\x1f\n" +
	"\vxhttp_extra\x183 \x01(\tR\n" +
	"xhttpExtra\x12\x1e\n" +
	"\n" +
	"encryption\x184 \x01(\tR\n" +
	"encryption\x12'\n" +
	"\x0fencryption_mode\x185 \x01(\tR\x0eencryptionMode\x12%\n" +
	"\x0eencryption_rtt\x186 \x01(\tR\rencryptionRtt\x12+\n" +
	"\x11encryption_ticket\x187 \x01(\tR\x10encryptionTicket\x12:\n" +
	"\x19encryption_server_padding\x188 \x01(\tR\x17encryptionServerPadding\x124\n" +
	"\x16encryption_private_key\x189 \x01(\tR\x14encryptionPrivateKey\x12:\n" +
	"\x19encryption_client_padding\x18: \x01(\tR\x17encryptionClientPadding\x12/\n" +
	"\x13encryption_password\x18; \x01(\tR\x12encryptionPassword\x12\x1d\n" +
	"\n" +
	"ech_enable\x18< \x01(\bR\techEnable\x12&\n" +
	"\x0fech_server_name\x18= \x01(\tR\rechServerName\x12\x14\n" +
	"\x05ratio\x18> \x01(\x01R\x05ratio\x12\x1b\n" +
	"\tcert_mode\x18? \x01(\tR\bcertMode\x12*\n" +
	"\x11cert_dns_provider\x18@ \x01(\tR\x0fcertDnsProvider\x12 \n" +
	"\fcert_dns_env\x18A \x01(\tR\n" +
	"certDnsEnv\"\xc0\x03\n" +
	"\x1dQueryServerProtocolConfigData\x128\n" +
	"\x18traffic_report_threshold\x18\x01 \x01(\x03R\x16trafficReportThreshold\x12#\n" +
	"\rpush_interval\x18\x02 \x01(\x03R\fpushInterval\x12#\n" +
	"\rpull_interval\x18\x03 \x01(\x03R\fpullInterval\x12\x1f\n" +
	"\vip_strategy\x18\x04 \x01(\tR\n" +
	"ipStrategy\x12/\n" +
	"\x03dns\x18\x05 \x03(\v2\x1d.ppanel.server.v1.DNSResolverR\x03dns\x12\x14\n" +
	"\x05block\x18\x06 \x03(\tR\x05block\x126\n" +
	"\boutbound\x18\a \x03(\v2\x1a.ppanel.server.v1.OutboundR\boutbound\x12>\n" +
	"\tprotocols\x18\b \x03(\v2 .ppanel.server.v1.ServerProtocolR\tprotocols\x12\x14\n" +
	"\x05total\x18\t \x01(\x03R\x05total\x12%\n" +
	"\x0etarget_version\x18\n" +
	" \x01(\tR\rtargetVersion\"\x96\x01\n" +
	"!QueryServerProtocolConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x04data\x18\x03 \x01(\v2/.ppanel.server.v1.QueryServerProtocolConfigDataR\x04dataB8Z6github.com/perfect-panel/server/api/server/v1;serverv1b\x06proto3"

var (
	file_api_server_v1_server_proto_rawDescOnce sync.Once
	file_api_server_v1_server_proto_rawDescData []byte
)

func file_api_server_v1_server_proto_rawDescGZIP() []byte {
	file_api_server_v1_server_proto_rawDescOnce.Do(func() {
		file_api_server_v1_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_server_v1_server_proto_rawDesc), len(file_api_server_v1_server_proto_rawDesc)))
	})
	return file_api_server_v1_server_proto_rawDescData
}

var file_api_server_v1_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_server_v1_server_proto_goTypes = []any{
	(*OnlineUser)(nil),                        // 0: ppanel.server.v1.OnlineUser
	(*PushOnlineUsersRequest)(nil),            // 1: ppanel.server.v1.PushOnlineUsersRequest
	(*UserTraffic)(nil),                       // 2: ppanel.server.v1.UserTraffic
	(*PushUserTrafficRequest)(nil),            // 3: ppanel.server.v1.PushUserTrafficRequest
	(*PushServerStatusRequest)(nil),           // 4: ppanel.server.v1.PushServerStatusRequest
	(*Result)(nil),                            // 5: ppanel.server.v1.Result
	(*ServerBasic)(nil),                       // 6: ppanel.server.v1.ServerBasic
	(*ServerConfigData)(nil),                  // 7: ppanel.server.v1.ServerConfigData
	(*GetServerConfigResponse)(nil),           // 8: ppanel.server.v1.GetServerConfigResponse
	(*ServerUser)(nil),                        // 9: ppanel.server.v1.ServerUser
	(*ServerUserListData)(nil),                // 10: ppanel.server.v1.ServerUserListData
	(*GetServerUserListResponse)(nil),         // 11: ppanel.server.v1.GetServerUserListResponse
	(*DNSResolver)(nil),                       // 12: ppanel.server.v1.DNSResolver
	(*Outbound)(nil),                          // 13: ppanel.server.v1.Outbound
	(*ServerProtocol)(nil),                    // 14: ppanel.server.v1.ServerProtocol
	(*QueryServerProtocolConfigData)(nil),     // 15: ppanel.server.v1.QueryServerProtocolConfigData
	(*QueryServerProtocolConfigResponse)(nil), // 16: ppanel.server.v1.QueryServerProtocolConfigResponse
	(*structpb.Struct)(nil),                   // 17: google.protobuf.Struct
	(*structpb.Value)(nil),                    // 18: google.protobuf.Value
}
var file_api_server_v1_server_proto_depIdxs = []int32{
	0,  // 0: ppanel.server.v1.PushOnlineUsersRequest.users:type_name -> ppanel.server.v1.OnlineUser
	2,  // 1: ppanel.server.v1.PushUserTrafficRequest.traffic:type_name -> ppanel.server.v1.UserTraffic
	6,  // 2: ppanel.server.v1.ServerConfigData.basic:type_name -> ppanel.server.v1.ServerBasic
	17, // 3: ppanel.server.v1.ServerConfigData.config:type_name -> google.protobuf.Struct
	7,  // 4: ppanel.server.v1.GetServerConfigResponse.data:type_name -> ppanel.server.v1.ServerConfigData
	9,  // 5: ppanel.server.v1.ServerUserListData.users:type_name -> ppanel.server.v1.ServerUser
	10, // 6: ppanel.server.v1.GetServerUserListResponse.data:type_name -> ppanel.server.v1.ServerUserListData
	18, // 7: ppanel.server.v1.Outbound.plugin_options:type_name -> google.protobuf.Value
	18, // 8: ppanel.server.v1.ServerProtocol.plugin_options:type_name -> google.protobuf.Value
	12, // 9: ppanel.server.v1.QueryServerProtocolConfigData.dns:type_name -> ppanel.server.v1.DNSResolver
	13, // 10: ppanel.server.v1.QueryServerProtocolConfigData.outbound:type_name -> ppanel.server.v1.Outbound
	14, // 11: ppanel.server.v1.QueryServerProtocolConfigData.protocols:type_name -> ppanel.server.v1.ServerProtocol
	15, // 12: ppanel.server.v1.QueryServerProtocolConfigResponse.data:type_name -> ppanel.server.v1.QueryServerProtocolConfigData
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_server_v1_server_proto_init() }
func file_api_server_v1_server_proto_init() {
	if File_api_server_v1_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_server_v1_server_proto_rawDesc), len(file_api_server_v1_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_server_v1_server_proto_goTypes,
		DependencyIndexes: file_api_server_v1_server_proto_depIdxs,
		MessageInfos:      file_api_server_v1_server_proto_msgTypes,
	}.Build()
	File_api_server_v1_server_proto = out.File
	file_api_server_v1_server_proto_goTypes = nil
	file_api_server_v1_server_proto_depIdxs = nil
}
