DROP TABLE IF EXISTS "email_task";
CREATE TABLE "email_task" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "subject" varchar(255)  NOT NULL,
    "content" text  NOT NULL,
    "recipient" text  NOT NULL,
    "scope" varchar(50)  NOT NULL,
    "register_start_time" TIMESTAMP(3) DEFAULT NULL,
    "register_end_time" TIMESTAMP(3) DEFAULT NULL,
    "additional" text,
    "scheduled" TIMESTAMP(3) NOT NULL,
    "interval" SMALLINT NOT NULL,
    "limit" BIGINT NOT NULL,
    "status" SMALLINT NOT NULL,
    "errors" text  NOT NULL,
    "total" BIGINT NOT NULL DEFAULT '0',
    "current" BIGINT NOT NULL DEFAULT '0',
    "created_at" TIMESTAMP(3) DEFAULT NULL,
    "updated_at" TIMESTAMP(3) DEFAULT NULL,
    PRIMARY KEY ("id")
);
