DROP TABLE IF EXISTS "email_task";
CREATE TABLE "task" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "type" SMALLINT NOT NULL,
    "scope" text,
    "content" text,
    "status" SMALLINT NOT NULL DEFAULT '0',
    "errors" text,
    "total" BIGINT NOT NULL DEFAULT '0',
    "current" BIGINT NOT NULL DEFAULT '0',
    "created_at" TIMESTAMP(3) DEFAULT NULL,
    "updated_at" TIMESTAMP(3) DEFAULT NULL,
    PRIMARY KEY ("id")
);
