CREATE TABLE IF NOT EXISTS "server_config_overrides"
(
    "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "server_id"   bigint                                                        NOT NULL,
    "ip_strategy" varchar(32) DEFAULT NULL,
    "dns"         text        DEFAULT NULL,
    "block"       text        DEFAULT NULL,
    "outbound"    text        DEFAULT NULL,
    "created_at"  TIMESTAMP(3) DEFAULT NULL,
    "updated_at"  TIMESTAMP(3) DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uni_server_config_overrides_server_id" UNIQUE ("server_id")
);
